
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.secret=${SECURITY_KEY}

logging.level.root=WARN
logging.level.cloud.zenixapp=INFO