spring.application.name=zenix

# Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/zenix_homologacao
spring.datasource.username=zenix_user
spring.datasource.password=Zenix_User
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
