api.security.secret=${SECURITY_KEY}

# Banco de Dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Adia a inicializacao do banco de dados para depois que o 'Hibernate' criar ou validar o esquema das tabelas
spring.jpa.defer-datasource-initialization=true
